
name: example-environment

channels:

  - conda-forge

dependencies:

  - numpy

  - psutil

  - toolz

  - matplotlib

  - dill

  - pandas

  - partd

  - bokeh

  - seaborn
  
  - xlrd
  
  - scikit-learn
  
  - scipy
  
  - statsmodels
  
cache: pip

install:
  - pip install codecov
  - pip install coverage

script: coverage run --source scikit_posthocs setup.py test

after_success:
  - codecov
