
name: example-environment

channels:

  - conda-forge
  
  - conda

dependencies:

  - numpy

  - psutil

  - toolz

  - matplotlib

  - dill

  - pandas

  - partd

  - bokeh

  - seaborn
  
  - xlrd
  
  - scikit-learn
  
  - PMCMRplus
  
  - scipy
  
  - statsmodels
  
  - scikit_posthocs
  
  - pip:
    - scikit-posthocs

  

