
name: example-environment

channels:

  - conda-forge
  
  - conda

pip:
  - scikit-posthocs

dependencies:

  - numpy

  - psutil

  - toolz

  - matplotlib

  - dill

  - pandas

  - partd

  - bokeh

  - seaborn
  
  - xlrd
  
  - scikit-learn
  
  - scipy
  
  - statsmodels
  
  - scikit-posthocs
  


  

