
name: example-environment

channels:

  - conda-forge
  
  - conda

pip:
  - scikit_posthocs

dependencies:

  - numpy

  - psutil

  - toolz

  - matplotlib

  - dill

  - pandas

  - partd

  - bokeh

  - seaborn
  
  - xlrd
  
  - scikit-learn
  
  - scipy
  
  - statsmodels
  
  - scikit_posthocs
  
  
    - scikit_posthocs

  

