
name: example-environment

channels:

  - conda-forge

dependencies:

  - numpy

  - psutil

  - toolz

  - matplotlib

  - dill

  - pandas

  - partd

  - bokeh

  - seaborn
  
  - xlrd
  
  - scikit-learn
  
  - scipy

  script: coverage run --source scikit_posthocs setup.py test
  


