
name: example-environment

channels:

  - conda-forge
  
  - conda

dependencies:

  - numpy

  - matplotlib

  - pandas

  - bokeh

  - seaborn
  
  - xlrd
  
  - scikit-learn
  
  - scipy
  
  - statsmodels

  - pip:
    - scikit-posthocs
  


  

